### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by sandeshraii** [sandeshraii/ContentManagementSystem#6]
Logo is not displayed as shown in the figure.
![image](https://user-images.githubusercontent.com/81347130/115136665-f4c78680-a040-11eb-90e9-c1966804188e.png)
Make sure you give a proper location to it.

**Comment by SumitHamal** [comment]
I have given the proper path location to logo. Please check it out.
![image](https://user-images.githubusercontent.com/81404105/115136725-6ef80b00-a041-11eb-9afb-430541d60fe0.png)
